services:
  - type: web
    name: tableros-api
    runtime: python
    region: oregon
    plan: free
    repo: https://github.com/danieln3m0/RemsPrueBack
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tableros-db
          property: connectionString
      - key: ECHO_SQL
        value: "false"
databases:
  - name: tableros-db
    plan: free
